language : c
script : 
    - cd logtool_staticlib_cpp && make liblog.so
    - cd ../all2string_lib_cpp && make a2str.a
    - cd ../all2string_lib_cpp && make a2str.so
    - cd ../gtest && make libgtest.so
    - cd ../gtest && make libgtest.a
compiler :
    - g++